#!/bin/bash

# Reload to see the effect of your current changes
# sketchybar --reload

source "$CONFIG_DIR/colors.sh" # Loads all defined colors

# This is a demo config to show some of the most important commands more easily.
# This is meant to be changed and configured, as it is intentionally kept sparse.
# For a more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

##### Bar Appearance #####
# Configuring the general appearance of the bar, these are only some of the
# options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar height=39        \
                 blur_radius=30   \
                 position=top     \
								 margin=10				\
                 sticky=off       \
								 shadow=on			\
								 y_offset=10		\
								 corner_radius=12 \
                 padding_left=12  \
                 padding_right=12 \
                 color=$BLACK

# ----------

# bar_config=(
# 	blur_radius=30
# 	color="$BASE"
# 	corner_radius=9
# 	height=40
# 	margin=10
# 	notch_width=0
# 	padding_left=18
# 	padding_right=10
# 	position=top
# 	shadow=on
# 	sticky=on
# 	topmost=off
# 	y_offset=10
# )

# ---------


##### Changing Defaults #####
# We now change some default values that are applied to all further items
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

sketchybar --default icon.font="SF Pro:Semi:14.0"  \
                     icon.color=$WHITE                 \
                     label.font="SF Pro:Semi:14.0" \
                     label.color=$WHITE                \
                     background.corner_radius=5        \
                     background.height=24              \
                     padding_left=1                        \
                     padding_right=1                       \
                     label.padding_left=3                  \
                     label.padding_right=3                 \
                     icon.padding_left=3                   \
                     icon.padding_right=0

# background.color=$ITEM_BG_COLOR   \


# -- Left Side Items --
source "$ITEM_DIR/spaces.sh" # ~/.config/sketchybar/items/spaces.sh
source "$ITEM_DIR/front_app.sh" # ~/.config/sketchybar/items/front_app.sh



# -- Right Side Items --
# source "$ITEM_DIR/volume.sh" # ~/.config/sketchybar/items/volume.sh
source "$ITEM_DIR/calendar.sh" # ~/.config/sketchybar/items/calendar.sh
source "$ITEM_DIR/wifi.sh" # ~/.config/sketchybar/items/wifi.sh
source "$ITEM_DIR/battery.sh" # ~/.config/sketchybar/items/battery.sh
source "$ITEM_DIR/bluetooth.sh" # ~/.config/sketchybar/items/bluetooth.sh




# ##### Adding Mission Control Space Indicators #####
# # Now we add some mission control spaces:
# # https://felixkratz.github.io/SketchyBar/config/components#space----associate-mission-control-spaces-with-an-item
# # to indicate active and available mission control spaces
#
# SPACE_ICONS=("1" "2" "3" "4" "5" "6" "7" "8" "9" "10")
#
# for i in "${!SPACE_ICONS[@]}"
# do
#   sid=$(($i+1))
#   sketchybar --add space space.$sid left                                 \
#              --set space.$sid space=$sid                                 \
#                               icon=${SPACE_ICONS[i]}                     \
#                               background.color=0x44ffffff                \
#                               background.corner_radius=5                 \
#                               background.height=20                       \
#                               background.drawing=off                     \
#                               label.drawing=off                          \
#                               script="$PLUGIN_DIR/space.sh"              \
#                               click_script="yabai -m space --focus $sid"
# done
#
# ##### Adding Left Items #####
# # We add some regular items to the left side of the bar
# # only the properties deviating from the current defaults need to be set
#
# sketchybar --add item space_separator left                         \
#            --set space_separator icon=                            \
#                                  padding_left=10                   \
#                                  padding_right=10                  \
#                                  label.drawing=off                 \
#                                                                    \
#            --add item front_app left                               \
#            --set front_app       script="$PLUGIN_DIR/front_app.sh" \
#                                  icon.drawing=off                  \
#            --subscribe front_app front_app_switched
#
# ##### Adding Right Items #####
# # In the same way as the left items we can add items to the right side.
# # Additional position (e.g. center) are available, see:
# # https://felixkratz.github.io/SketchyBar/config/items#adding-items-to-sketchybar
#
# # Some items refresh on a fixed cycle, e.g. the clock runs its script once
# # every 10s. Other items respond to events they subscribe to, e.g. the
# # volume.sh script is only executed once an actual change in system audio
# # volume is registered. More info about the event system can be found here:
# # https://felixkratz.github.io/SketchyBar/config/events
#
# sketchybar --add item clock right                              \
#            --set clock   update_freq=10                        \
#                          icon=                                \
#                          script="$PLUGIN_DIR/clock.sh"         \
#                                                                \
#            --add item volume right                             \
#            --set volume  script="$PLUGIN_DIR/volume.sh"        \
#            --subscribe volume volume_change                    \
#                                                                \
#            --add item battery right                            \
#            --set battery script="$PLUGIN_DIR/battery.sh"       \
#                          update_freq=120                       \
#            --subscribe battery system_woke power_source_change



##### Finalizing Setup #####
# The below command is only needed at the end of the initial configuration to
# force all scripts to run the first time, it should never be run in an item script.

sketchybar --update
